version: "3.9"
services:
  quiz-service:
    image: carodaems/api-quiz
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume:
